# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 353dcd7565eecc311aeaf361c312c0dc43ff033f72ec42c73864c13f8af8cfb346792bbb39fe96a0ebaf8084d21c62b1f8abadef96e2fe1f459fd0b0db1bcb56

test:
  secret_key_base: 99e9f22a33c8d7eb320e0753732f2763fe987568199931de30ad5b4178c7a7afffe06b4ce660e270c15015ebf69ff7ae93ee678aafdfb4e911cc2d023de339d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
